load('api_config.js');
load('api_arduino_ssd1306.js');
load('api_timer.js');

// FFI Wrappers

Adafruit_SSD1306._spl = ffi('void ssd1306_splash(void *, void *)');
Adafruit_SSD1306._proto.splash = function (data) { Adafruit_SSD1306._spl(this.ssd, data); };
Adafruit_SSD1306._dbm = ffi('void ssd1306_drawBitmap(void *, void *, int, int, int, int)');
Adafruit_SSD1306._proto.drawBitmap = function (data, x, y, w, h) { Adafruit_SSD1306._dbm(this.ssd, data, x, y, w, h); };
let free = ffi('void free(void *)');

// Polyfills

let atob = atob || function (str) { return ffi('void *atob(void *, int)')(str, str.length); };


// Display 

let d = Adafruit_SSD1306.create_i2c(Cfg.get('app.ssd1306_reset_pin'), Adafruit_SSD1306.RES_128_64);
d.begin(Adafruit_SSD1306.SWITCHCAPVCC, 0x3C, true);


// Main
function main() {
  let logo2 = atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAeAAAAAAAAAD4AAAAAAAAAfgAAAAAAAAD8AAAAAAAAAfwAAAAAAAAB/AAAAAAAAAP4AAAAAAAAB/gAAAAAAAAP+AAAAAAAAAf4AAAAAAAB//AAAAAAAA//8AAAAAAAP//wAAAAAAD///AAAAAAAf//+AAAAAAB///8AAAAAAAYA/4AAAAAAAAA/wAAAAAAAAB/gAAAAAAAAD/AAAAAAAAAH+AAAAAAAAAf8AAAAAAAAA/4AAAAAAAAD/gAAAAAAAAP/AAAAAAAAAf8AAAAAAAAB/4AAAAAAAAH/gAAAAAAAAf/AAAAAAAAB/8AAAAAAAAD/wAAAAAAAAP/gAAAAAAAA/+AAAAAAAAD/4AAAAAAAAD/gAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAQAgBACAAAAf8/5/z/gAAD///////AAAP//////8AAA8f4/x/jwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
  d.clearDisplay();
  d.drawBitmap(logo2, 0, 0, 64, 64);
  d.setTextColor(Adafruit_SSD1306.WHITE);
  d.setTextSize(2);
  d.setCursor(65, 20)
  d.write("10.0")
  d.setTextSize(1);
  d.setCursor(100, 35)
  d.write("cm")
  d.display();
  free(logo2);
}

// Init
function init() {
  let logo = atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAA/4AAAAAAAAAAAAAAAAAAAP8AAAAAAAA7gAQGAAAAAAD/AAAAAAAANgAABgAAAAA//wAAAAAAHn8+fH4AAAAA//4AAAAAADN2ZvTOAAAAA//+AAAAAAAhtsbFhgAAAB///wAAAAAAYbbCxYYAAAA///+AAAAAAGG2wsWGAAAAH///wAAAAAAhtsbFhgAAAAMAP+AAAAAAMzZuxM4AAAAAAB/wAAAAAB82PsT+AAAAAAAH+AAAAAAAAEIAAAAAAAAAB/wAAAAAAABmAAAAAAAAAAP8AAAAAAAAPAAAAAAAAAAB/gAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAAAAAAAA/4AAAAAAAAAAAAAAAAAAAP/AAAAAgAAAYAAAAAAAAAD/wAAAAYAAAGAAAAAAAAAA/+AA/HvxiefjeAAAAAAAAH/gAO7dkZs35swAAAAAAAB/4ADHjZueFmzEAAAAAAAAf/AAx/2b1h54eAAAAAAAAH/wAMf9ivYefDwAAAAAAAB/8ADHhY52HmbGAAAAAAAAf/AAxs2OYzZjxgAAAAAAAB/wAMb4xmPmY3wAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgBACAAAAAAAAAAAAAAAAD/n/P+P8AAAAAAAAAAAAAB///////gAAAAAAAAAAAAAf//////4AAAAAAAAAAAAAHj/H/P+eAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
  d.clearDisplay();
  d.splash(logo);
  d.display();
  free(logo);
  Timer.set(3000, false, main, null);
}


init();